dependencies:
  - base
  - wai
  - http-types
  - warp
  - bytestring
  - string-conversions
  - aeson
  - servant
  - servant-server
  - servant-docs
  - servant-swagger
  - directory
  - process
  - transformers

executables:
  server:
    main: Main.hs
